apiVersion: v1
kind: Service
metadata:
  name: heart-disease-mlops-service
spec:
  type: LoadBalancer
  selector:
    app: heart-disease-mlops-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
